### ISSUE TITLE
Is BluenetLib still required?

### ISSUE THREAD

**Issue by hillstub** [crownstone/crownstone-lib-python-core#1]
In file `crownstone_core/packets/MicroappPacket.py` there's (still) a reference to the BluenetLib:
```
from BluenetLib.lib.util.fletcher import fletcher32_uint8Arr
```

Is that intentional? (it's not in the `requirements.txt` file).
Thanks in advance!

**Comment by AlexDM0** [comment]
Hi, sorry, that’s sloppiness on my side. I’ll remove it tomorrow! Bluenet is not required anymore.

Thanks for the heads up!

________________________________

**Comment by hillstub** [comment]
No worries - I guess we're all human ;-).

Would you be able to match the versions of the dependencies in `requirements.txt` as well when you're updating the packages? (if that's possible at all).

**Comment by AlexDM0** [comment]
I’m not sure what you mean with matching the versions? These libs are different, and the core is used for multiple libraries. The versions will not be identical.

________________________________

**Comment by hillstub** [comment]
I meant that e.g. in `crownstone-lib-python-ble` the `requirements.txt` have (among others) the following dependencies:
```
crownstone-core==0.5.6
```

While  `crownstone-lib-python-uart`  has
```
crownstone-core==0.5.7
```

Would be great if these versions would match so both packages can be used alongside. Sorry, I might have a weird use case: I'm sending the on/off command to a crownstone using the uart package. Unfortunately, that doesn't always come through, so I'd like to double-check the state using the ble package.

**Comment by AlexDM0** [comment]
Hi, I've updated the core, and the dependencies for the other libraries. Just this once, they match, but this will not be the case forever. Since we use semver and I don't expect the core to be breaking any time soon, I have set the requirements to >=0.5.8

This should future proof it for a while.

Regards
