### ISSUE TITLE
Relay attribute in switch state always returns False

### ISSUE THREAD

**Issue by RicArch97** [crownstone/crownstone-lib-python-core#4]
in `crownstone_core/protocol/SwitchState.py` line 14
```
self.relay = (rawSwitchState & 0x80 == 1)
```
With `rawSwitchState` being a value from 0-100, that statement always returns `False`.

**Comment by vliedel** [comment]
`rawSwitchState` should be a combined value of 1 bit relay, and 7 bits dimmer. Maybe you're using the class in the wrong context?

**Comment by RicArch97** [comment]
This was based on received uart data with the uart lib, where the relay value of a non-dimmable Crownstone is always False.

**Comment by vliedel** [comment]
Could you maybe give more details? Which event is this, and from what UART message is it originating? What lib versions are you using and which firmware version?

**Comment by RicArch97** [comment]
Uart lib version 2.0.0

Topic: UartTopic.newDataAvailable 

data:
```
AdvType.EXTERNAL_STATE
crownstoneId:             1
switchState:              SwitchState(intensity=100, relay=False, dimmer=100)
flags:                  
    dimmerReady:         True
    dimmingAllowed:      True
    hasError:            False
    switchLocked:        False
    timeIsSet:           True
    switchCraftEnabled:  False
    tapToToggleEnabled:  False
    behaviourOverridden: True
temperature:              40
powerFactor:              1.0
powerUsageReal:           1.125
powerUsageApparent:       1.125
accumulatedEnergy:        24192
rssiOfExternalCrownstone: 0
timestamp:                1620323574
uniqueIdentifier:         11510
validation:               250
```

This was when a non-dimmable Crownstone was switched on.

**Comment by vliedel** [comment]
Ok, so this should originate from the service data that was received from the mesh. That indeed includes both relay and dimmer state.
When you turn the crownstone off and on again, do you hear it clicking (twice)?

**Comment by vliedel** [comment]
Also: notice how it tells you that `dimmingAllowed` is True, so it uses the dimmer instead of the relay.

**Comment by RicArch97** [comment]
I accidentally copied data from a Crownstone that indeed has dimming enabled, here's an other one:
```
AdvType.EXTERNAL_STATE
crownstoneId:             14
switchState:              SwitchState(intensity=100, relay=False, dimmer=0)
flags:                  
    dimmerReady:         True
    dimmingAllowed:      False
    hasError:            False
    switchLocked:        False
    timeIsSet:           True
    switchCraftEnabled:  False
    tapToToggleEnabled:  False
    behaviourOverridden: True
temperature:              39
powerFactor:              1.0
powerUsageReal:           -4.375
powerUsageApparent:       -4.375
accumulatedEnergy:        277760
rssiOfExternalCrownstone: 0
timestamp:                1620324285
uniqueIdentifier:         12221
validation:               250
```

**Comment by vliedel** [comment]
Well, that definitely looks like a bug :) With an intensity of 100, either the relay should be True, or dimmer should be 100.

**Comment by vliedel** [comment]
So yeah, `self.relay = (rawSwitchState & 0x80 == 1)` should be `self.relay = (rawSwitchState & 0x80 == 0x80)` or `self.relay = (rawSwitchState & 0x80 != 0)`.

**Comment by vliedel** [comment]
Fixed in https://github.com/crownstone/crownstone-lib-python-core/commit/2ad5ef07ddfdf732cc4b8c5b5f115987759a4675
