### ISSUE TITLE
Timestamp calculation is incorrect

### ISSUE THREAD

**Issue by AlexDM0** [crownstone/crownstone-lib-python-core#5]
When converting the timestamp of a Crownstone from the 'wall-clock' time to an Unix timestamp, there is a convenience method here: https://github.com/crownstone/crownstone-lib-python-core/blob/master/crownstone_core/util/Timestamp.py#L37

However, the line of code to calculate the difference (also used here: https://github.com/crownstone/crownstone-lib-python-core/blob/master/crownstone_core/util/Timestamp.py#L17) does not take daylight saving time into account.

At 13 Aug 2021 it gave an offset of 3600 seconds from UTC, which should be 7200 [since UTC never has daylight saving time](https://en.wikipedia.org/wiki/UTC_offset#Daylight_saving_time).

At the reconstruction this only becomes an issue when the additional hour will impact one of the 2 MSB's, since those are the only ones used for the reconstruction.

This should be fixed, even for this edge case, and we should fix the convenience function so it does what you'd expect.

Finally we might want to revisit the [timestamps we put in the service data structs](https://github.com/crownstone/crownstone-lib-python-core/blob/master/crownstone_core/packets/serviceDataParsers/containers/AdvCrownstoneState.py)

I think we could argue that these need to be converted to Unix timestamps before we push them to the user.

Cheers

**Comment by vliedel** [comment]
Looks like we can use `time.localtime().tm_gmtoff` instead.

**Comment by vliedel** [comment]
Fixed with https://github.com/crownstone/crownstone-lib-python-core/commit/e50eaae8680614c030df186aa06f13c9b20ac9ba

**Comment by vliedel** [comment]
Regarding the timestamp in the service data: the timestamp is already a unix timestamp, but UTC. If you want to print it, you can simply use `time.asctime(time.gmtime(timestamp))`.

Changing the data you get in the `BleTopics.advertisement` is something for another time, as I'd rather have it typed and documented in code as well.
